# Generated by Django 4.1.5 on 2023-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
