# Generated by Django 4.1.5 on 2023-03-02 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_reg_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='account_pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='icon',
            field=models.CharField(default='up', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
