# Generated by Django 4.1.5 on 2023-03-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_reg_account_pin_alter_transfer_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='mode',
            field=models.CharField(default='modal', max_length=50),
        ),
    ]
