# Generated by Django 4.1.5 on 2023-05-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transfer_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='Approved', max_length=50),
        ),
    ]
