# Generated by Django 4.1.5 on 2023-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_transfer_date_alter_transfer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='up', max_length=50)),
                ('color', models.CharField(default='green', max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(default='WIRE TRANSFER', max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Approved', max_length=50)),
            ],
        ),
    ]
