# Generated by Django 4.1.5 on 2023-06-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_transfer_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
    ]
