# Generated by Django 4.2.5 on 2025-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_history_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=50),
        ),
    ]
