# Generated by Django 4.2.5 on 2025-08-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_reg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='account_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='dp',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
